In [1]:
######################################################################################
#########################INFO ABOUT ALL DATAFRAMES/OBJECTS/DICTIONARIES/OTHER DATA######################
'''
balanceSummaryDf -> Summary about balance of all months + some other stats
allTransactionsDf -> Details of all transactions by the person
profileDataDict -> Store all info about the person, current balance, name, age etc
keySummary -> Stores all key features about the financial analysis
investmentDataDict -> Stores summary of all types of investment types data
categoryObjects -> Stores details in object for all categories
categoryDataDf -> Stores details in a table for all categories
categoriesDict -> Stores details about categories with key as category name
latestMonthCategoryObjects -> Stores details in object about all categories for the latest month
latestMonthCategoriesDataDf -> Stores details in table about all cateogries for the latest month
equityDataObject -> Stores info about equity investments along with all holdings in an object
equityHoldingsDf -> Stores all equity holdings in a table
insuranceSummaryObj -> Summary of insurance policy of the person in an object
mutualFundsObject -> Summary of all mutual fund investments


demographicsDict -> Info about demographics of the person
lowLimitBudget -> Stores lower limit of income split into different categories
upperLimitBudget -> Stores upper limit of income split into different categories
budgetEval -> Dictionary with how the person stands on-par with the budget split in each category
featureFlags -> Dictionary with List of features describing a person's finance with boolean values
personalityIdentifier -> Dictionary with boolean values indicating if the person fits into a specific finance personality
miscTypes -> Dictionary to identify which miscellaneous segment does the user lie under

possibleNudgesForUser -> List of objects with details of possible personalized nudges for the user


'''

"\nbalanceSummaryDf -> Summary about balance of all months + some other stats\nallTransactionsDf -> Details of all transactions by the person\nprofileDataDict -> Store all info about the person, current balance, name, age etc\nkeySummary -> Stores all key features about the financial analysis\ninvestmentDataDict -> Stores summary of all types of investment types data\ncategoryObjects -> Stores details in object for all categories\ncategoryDataDf -> Stores details in a table for all categories\ncategoriesDict -> Stores details about categories with key as category name\nlatestMonthCategoryObjects -> Stores details in object about all categories for the latest month\nlatestMonthCategoriesDataDf -> Stores details in table about all cateogries for the latest month\nequityDataObject -> Stores info about equity investments along with all holdings in an object\nequityHoldingsDf -> Stores all equity holdings in a table\ninsuranceSummaryObj -> Summary of insurance policy of the person in an object\nmutualFundsObject -> Summary of all mutual fund investments\n\n\ndemographicsDict -> Info about demographics of the person\nlowLimitBudget -> Stores lower limit of income split into different categories\nupperLimitBudget -> Stores upper limit of income split into different categories\nbudgetEval -> Dictionary with how the person stands on-par with the budget split in each category\nfeatureFlags -> Dictionary with List of features describing a person's finance with boolean values\npersonalityIdentifier -> Dictionary with boolean values indicating if the person fits into a specific finance personality\nmiscTypes -> Dictionary to identify which miscellaneous segment does the user lie under\n\npossibleNudgesForUser -> List of objects with details of possible personalized nudges for the user\n\n\n"

In [2]:
# Importing libraries
import pandas as pd
import numpy as np
import csv
import json
from datetime import date
import datetime
import math

In [3]:
# Setting mobile number for the context
mobileNumber = "9987600001"

In [4]:
# Some presets for better viewing of data
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [5]:
# Converting json to csv
def json2csv(json_name, csv_name, key, subKey):
    with open(json_name) as json_file:
        data = json.load(json_file)
    transaction_data = data[key][subKey]
    data_file = open(csv_name, 'w') 
    csv_writer = csv.writer(data_file)
    count = 0
    for tran in transaction_data:
        if count == 0: 
            # Writing headers of CSV file 
            header = tran.keys()
            csv_writer.writerow(header) 
            count += 1
        # Writing data of CSV file 
        csv_writer.writerow(tran.values())
    data_file.close()

In [6]:
json2csv('../data/Deposit/3742409078.json', '../data/Deposit/3742409078.csv', 'Transactions', 'Transaction')
df = pd.read_csv('../data/Deposit/3742409078.csv')

In [7]:
df.head()

,type,amount,narration,currentBalance,transactionTimestamp,txnId,mode,reference,valueDate
0,DEBIT,1050.00,UPI-AYAN SHEIKH-AYAN.SHEIKH@YBL-SBIN2508461-03692464306,36572.78,2022-01-13T09:57:40+05:30,NaN,OTHER,NaN,2022-01-13
1,DEBIT,1050.00,EAW-381510XXXXXX7741-CPCN6427-BHARUCH,35522.78,2022-01-15T07:10:06+05:30,NaN,OTHER,NaN,2022-01-915
2,DEBIT,603.75,UPI-PLAYERZPOT MEDIA PVT-PLAYERZPOT@PAYTM-PYTM8576012-133572,34919.03,2022-01-15T09:07:50+05:30,NaN,OTHER,NaN,2022-01-15
3,CREDIT,1050.00,IMPS-803782298818-FIDUCIARY BILLING SO-YESB-XXXXXXXXXXX1143-,35969.03,2022-01-15T09:25:34+05:30,NaN,OTHER,NaN,2022-01-15
4,CREDIT,5250.00,IMPS-791730016004-Prasad Rathod-PYTM-XXXXXXXXXX2721-DOMESTIC,41219.03,2022-01-15T10:48:22+05:30,NaN,OTHER,NaN,2022-01-15

In [8]:
# Function to load json as dict
def loadJson(filePath):
    with open(filePath) as json_file:
        jsonData = json.load(json_file)
    return jsonData

In [9]:
# Reading bank analysis json
bankAnalysisfilePath = '../data/Bank-Analysis-Sample/3742420758.json'
bankAnalysisData = loadJson(bankAnalysisfilePath)

# bankAnalysisfilePathPerson2 = '../data/Bank-Analysis-Sample/3742421256.json'
# bankAnalysisDataPerson2 = loadJson(bankAnalysisfilePathPerson2)

# Reading Deposit, Equities, Insurance Policy, Mutual Fund Jsons
depositFilePath = '../data/Deposit/3742420758.json'

# depositFilePathPerson2 = '../data/Deposit/3742421256.json'
equitiesFilePath = '../data/Equities/3234827890.json'
insuranceFilePath = '../data/Insurance Policy/5234562290.json'
mutualFundFilePath = '../data/Mutual Fund/8934157590.json'

depositData = loadJson(depositFilePath)
# depositDataPerson2 = loadJson(depositFilePathPerson2)
equitiesData = loadJson(equitiesFilePath)
insuranceData = loadJson(insuranceFilePath)
mutualFundData = loadJson(mutualFundFilePath)

In [10]:
# Dropping useless keys
removedKey = bankAnalysisData.pop("accountWiseAnalysis", None)
removedKey = bankAnalysisData.pop("frequentCredits", None)
removedKey = bankAnalysisData.pop("frequentDebits", None)
removedKey = bankAnalysisData.pop("loanCreditsAnalysis", None)
removedKey = bankAnalysisData.pop("counterPartyAnalysis", None)
removedKey = bankAnalysisData.pop("paymentTypeAnalytics", None)
removedKey = bankAnalysisData.pop("bounceAnalysis", None)
removedKey = bankAnalysisData.pop("top5FundTransfer", None)

In [11]:
# Storing keys to be used in analysis
analysis_keys = [] 
for analysis_key in bankAnalysisData:
    analysis_keys.append(analysis_key)

In [12]:
analysis_keys

['accountProfiles',
 'overallAnalysis',
 'investmentAnalysis',
 'completeCategoryWiseAnalysis',
 'allTransactions',
 'abbTables']

In [13]:
# Making balanceSummaryDf using 'abbTable' key in bankAnalysisData
balanceSummaryList = bankAnalysisData['abbTables']['overall']['monthlyData']
balanceSummaryDf = pd.DataFrame.from_dict(balanceSummaryList)
balanceSummaryDf

,monthYear,month,year,eodBalOn5,eodBalOn10,eodBalOn15,eodBalOn20,eodBalOn25,eodBalTotal,eodBalAvg
0,November-2021,11,2021,NaN,NaN,17387.30,30783.42,25093.87,73264.59,24421.53
1,December-2021,12,2021,6423.76,81762.56,26276.86,3769.46,3185.21,121417.85,24283.57
2,January-2022,1,2022,13033.86,62823.36,27550.81,4917.06,2624.71,110949.80,22189.96
3,February-2022,2,2022,7161.91,97209.56,31759.56,2590.76,2780.76,141502.55,28300.51
4,March-2022,3,2022,30388.52,16063.83,69140.33,9151.63,8440.08,133184.39,26636.88
5,April-2022,4,2022,20146.14,110672.21,26001.56,6955.01,10749.92,174524.84,34904.97
6,May-2022,5,2022,7208.63,68591.70,387377.79,37589.92,40244.22,541012.26,108202.45
7,June-2022,6,2022,5026.77,55122.17,NaN,NaN,NaN,60148.94,30074.47

In [14]:
# Making allTransactionDf using 'allTransactions' key in bankAnalysisData
allTransactionsList = bankAnalysisData['allTransactions']
allTransactionsDf = pd.DataFrame.from_dict(allTransactionsList)
allTransactionsDf["id"] = allTransactionsDf.index + 1

In [15]:
allTransactionsDf.tail()

,id,reference,narration,counterParty,paymentMode,type,amount,balance,dateOfTransaction,category,subcategory,account,merchantName,categoryCode,bank
547,548,,ACH D- TP ACH ICICI BANK-770673641,ICICI BANK,ECS,DEBIT,2898.45,48833.17,2022-06-14T04:39:18,EMIs,OTHER,,Unknown,EMI,HDFC Bank
548,549,,ACH D- TP ACH ICICI BANK-206985646,ICICI BANK,ECS,DEBIT,12180.90,36652.27,2022-06-14T05:14:18,EMIs,OTHER,,Unknown,EMI,HDFC Bank
549,550,,ACH D- FULLERTONINDCREDITCL-939756507532,FULLERTONINDCREDITCL,ECS,DEBIT,18858.45,17793.82,2022-06-14T09:45:34,EMIs,OTHER,,Unknown,EMI,HDFC Bank
550,551,,UPI-ATHAR KAMAL-Q586821563@YBL-ICIC1580894-602302227700-MEDI,ATHAR KAMAL,UPI,DEBIT,1659.65,16134.17,2022-06-14T13:07:50,Merchant Expenditure,OTHER,,Unknown,MERCHANT_EXPENDITURE,HDFC Bank
551,552,,UPI-BP PETROL PUMP UMA -Q19258285@YBL-YESB4YBLUPI-891170647,BP PETROL PUMP UMA,UPI,DEBIT,950.00,15184.17,2022-06-14T13:21:58,Utilities,FUEL,,Bharat Petroleum Co. Ltd,UTILITIES,HDFC Bank

In [16]:
# Profile data using depositData and "accountProfiles" key in analysis data

profileDataDict = {}

profileDataDict["name"] = depositData["Profile"]["Holders"]["Holder"][0]["name"]

# Calculating age
today = date.today()
dob = datetime.datetime.strptime(depositData["Profile"]["Holders"]["Holder"][0]["dob"], "%Y-%m-%d")
age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))

profileDataDict["dob"] = depositData["Profile"]["Holders"]["Holder"][0]["dob"]
profileDataDict["age"] = age
profileDataDict["address"] = depositData["Profile"]["Holders"]["Holder"][0]["address"]
# profileDataDict["mobile"] = depositData["Profile"]["Holders"]["Holder"][0]["mobile"]
profileDataDict["mobile"] = mobileNumber
profileDataDict["email"] = depositData["Profile"]["Holders"]["Holder"][0]["email"]
profileDataDict["currentBalance"] = depositData["Summary"]["currentBalance"]
profileDataDict["accountType"]  = depositData["Summary"]["type"]

profileDataDict["bank"] = bankAnalysisData["accountProfiles"][0]["Account"]["bank"]
profileDataDict["dataStartDate"] = bankAnalysisData["accountProfiles"][0]["summary"]["transactionStartDate"]
profileDataDict["dataEndDate"] = bankAnalysisData["accountProfiles"][0]["summary"]["transactionEndDate"]
profileDataDict["monthsOfData"] = balanceSummaryDf.shape[0]
profileDataDict

{'name': 'MR.AYAN BHANUSHALI',
 'dob': '2000-10-10',
 'age': 22,
 'address': '501 HARIKRISHNA PUNAGAM SURAT',
 'mobile': '9987600001',
 'email': 'ayan.bhanushali@gmail.com',
 'currentBalance': '15184.17',
 'accountType': 'SAVINGS',
 'bank': 'HDFC Bank',
 'dataStartDate': '2021-11-13',
 'dataEndDate': '2022-06-14',
 'monthsOfData': 8}

In [18]:
# Dumping profile data into json
profileDataJsonPath = '../output-data/profileData-' + mobileNumber + '.json'
with open(profileDataJsonPath, 'w') as fp:
    json.dump(profileDataDict, fp)

In [19]:
# Creating summary of financial details using overallAnalysis key in bankAnalysisData

keySummary = {} # Stores all key features about the financial analysis

keySummary["totalAccounts"] = bankAnalysisData["overallAnalysis"]["totalAccounts"]
keySummary["creditDebitRatio"] = bankAnalysisData["overallAnalysis"]["creditDebitRatio"]
keySummary["totalCreditTxn"] = bankAnalysisData["overallAnalysis"]["totalCreditTxn"]
keySummary["totalCreditAmount"] = bankAnalysisData["overallAnalysis"]["totalCreditAmount"]
keySummary["totalDebitTxn"] = bankAnalysisData["overallAnalysis"]["totalDebitTxn"]
keySummary["totalDebitAmount"] = bankAnalysisData["overallAnalysis"]["totalDebitAmount"]
keySummary["avgMonthlyBalance"] = bankAnalysisData["overallAnalysis"]["avgMonthlyBalance"]
keySummary["last3MonthsAvgMonthlyBalance"] = bankAnalysisData["overallAnalysis"]["last3MonthsAvgMonthlyBalance"]
keySummary["last6MonthsAvgMonthlyBalance"] = bankAnalysisData["overallAnalysis"]["last6MonthsAvgMonthlyBalance"]
keySummary["last3MonthAvgDebitAmount"] = bankAnalysisData["overallAnalysis"]["last3MonthAvgDebitAmount"]
keySummary["last3MonthAvgCreditAmount"] = bankAnalysisData["overallAnalysis"]["last3MonthAvgCreditAmount"]
keySummary["volatilityOfBalance"] = bankAnalysisData["overallAnalysis"]["volatilityOfBalance"]

keySummary

{'totalAccounts': 1,
 'creditDebitRatio': 0.97,
 'totalCreditTxn': 71,
 'totalCreditAmount': 1715211.56,
 'totalDebitTxn': 481,
 'totalDebitAmount': 1761167.89,
 'avgMonthlyBalance': 27549.54,
 'last3MonthsAvgMonthlyBalance': 37663.26,
 'last6MonthsAvgMonthlyBalance': 29892.27,
 'last3MonthAvgDebitAmount': 402461.03,
 'last3MonthAvgCreditAmount': 384475.64,
 'volatilityOfBalance': 1.72}

In [20]:
# Investment data from "investmentAnalysis" key of bank-analysis data

# investmentTypes = ["Dividends", "Mutual Funds", "Stocks & Options", "Fixed/Recurring Deposits"]

investmentTypes = bankAnalysisData["investmentAnalysis"]["investmentSubCategoryAnalysis"].keys()
print(investmentTypes)
investmentDataDict = {}


# Brief summary
investmentDataDict["totalCreditAmount"] = bankAnalysisData["investmentAnalysis"]["overall"]["overallInvestmentAnalysis"]["totalCreditAmount"] 
investmentDataDict["monthlyAverageCreditAmount"] = bankAnalysisData["investmentAnalysis"]["overall"]["overallInvestmentAnalysis"]["monthlyAverageCreditAmount"] 
investmentDataDict["totalDebitAmount"] = bankAnalysisData["investmentAnalysis"]["overall"]["overallInvestmentAnalysis"]["totalDebitAmount"] 
investmentDataDict["monthlyAverageDebitAmount"] = bankAnalysisData["investmentAnalysis"]["overall"]["overallInvestmentAnalysis"]["monthlyAverageDebitAmount"]  

investmentDataDict["subCategoryAnalysis"] = {}
# Subcategory analysis
for invType in investmentTypes:
    investmentDataDict["subCategoryAnalysis"][invType] = {}
    investmentDataDict["subCategoryAnalysis"][invType]["totalCreditAmount"] = bankAnalysisData["investmentAnalysis"]["investmentSubCategoryAnalysis"][invType]["overallInvestmentAnalysis"]["totalCreditAmount"]
    investmentDataDict["subCategoryAnalysis"][invType]["monthlyAverageCreditAmount"] = bankAnalysisData["investmentAnalysis"]["investmentSubCategoryAnalysis"][invType]["overallInvestmentAnalysis"]["monthlyAverageCreditAmount"]
    investmentDataDict["subCategoryAnalysis"][invType]["totalDebitAmount"] = bankAnalysisData["investmentAnalysis"]["investmentSubCategoryAnalysis"][invType]["overallInvestmentAnalysis"]["totalDebitAmount"]
    investmentDataDict["subCategoryAnalysis"][invType]["monthlyAverageDebitAmount"] = bankAnalysisData["investmentAnalysis"]["investmentSubCategoryAnalysis"][invType]["overallInvestmentAnalysis"]["monthlyAverageDebitAmount"]

investmentDataDict

dict_keys(['Dividends', 'Mutual Funds', 'Stocks & Options', 'Fixed/Recurring Deposits'])

{'totalCreditAmount': 7101.05,
 'monthlyAverageCreditAmount': 887.63,
 'totalDebitAmount': 4000.0,
 'monthlyAverageDebitAmount': 500.0,
 'subCategoryAnalysis': {'Dividends': {'totalCreditAmount': 100.0,
   'monthlyAverageCreditAmount': 12.5,
   'totalDebitAmount': 0.0,
   'monthlyAverageDebitAmount': 0.0},
  'Mutual Funds': {'totalCreditAmount': 0.0,
   'monthlyAverageCreditAmount': 0.0,
   'totalDebitAmount': 4000.0,
   'monthlyAverageDebitAmount': 500.0},
  'Stocks & Options': {'totalCreditAmount': 1.05,
   'monthlyAverageCreditAmount': 0.13,
   'totalDebitAmount': 0.0,
   'monthlyAverageDebitAmount': 0.0},
  'Fixed/Recurring Deposits': {'totalCreditAmount': 7000.0,
   'monthlyAverageCreditAmount': 875.0,
   'totalDebitAmount': 0.0,
   'monthlyAverageDebitAmount': 0.0}}}

In [21]:
# Category wise transaction data summary using "completeCategoryWiseAnalysis" key from bank analysis data

categoryTypes = []
for catType in bankAnalysisData["completeCategoryWiseAnalysis"]["overallCategoryWiseAnalysis"]:
    categoryTypes.append(catType)

categoryTypes

categoryObjects = []  # Store all category details in object form
categoriesDict = {} # Stores all category details with category name as keys

for i in range(len(categoryTypes)):
    categoryDict = { "id": i+1, "categoryName": categoryTypes[i]}
    categoryDict.update(bankAnalysisData["completeCategoryWiseAnalysis"]["overallCategoryWiseAnalysis"][categoryTypes[i]])
    
    # Dropping useless keys
    removedKey = categoryDict.pop("minimumCreditAmount", None)
    removedKey = categoryDict.pop("maximumCreditAmount", None)
    removedKey = categoryDict.pop("minimumDebitAmount", None)
    removedKey = categoryDict.pop("maximumDebitAmount", None)
    removedKey = categoryDict.pop("volatilityCredit", None)
    removedKey = categoryDict.pop("volatilityDebit", None)   
    removedKey = categoryDict.pop("avgCreditAmount", None)
    removedKey = categoryDict.pop("avgDebitAmount", None)       
    removedKey = categoryDict.pop("last6MonthAvgCreditAmount", None) 
    removedKey = categoryDict.pop("last12MonthAvgDebitAmount", None)
    removedKey = categoryDict.pop("last6MonthAvgDebitAmount", None) 
    removedKey = categoryDict.pop("last12MonthAvgCreditAmount", None)

    categoryObjects.append(categoryDict)
    categoriesDict[categoryTypes[i]] = categoryDict

categoriesDataDf = pd.DataFrame.from_dict(categoryObjects)
categoriesDataDf

,id,categoryName,totalCreditAmount,totalDebitAmount,totalCreditTxn,totalDebitTxn,totalCreditDebitAmount,avgMonthlyCredit,avgMonthlyDebit,last3MonthAvgCreditAmount,last3MonthAvgDebitAmount,categoryCode
0,1,Credit Card Payment,0.00,5985.00,0,1,5985.00,0.00,0.00,0.00,0.00,CREDIT_CARD_PAYMENT
1,2,Salary,580726.45,0.00,7,0,580726.45,2791.45,2791.45,3708.08,3708.08,SALARY
2,3,Entertainment,0.00,405.65,0,1,405.65,0.00,0.00,0.00,0.00,ENTERTAINMENT
3,4,Personal Care,0.00,5727.55,0,1,5727.55,0.00,0.00,0.00,0.00,PERSONAL_CARE
4,5,Transfer to Wallet,0.00,13140.40,0,11,13140.40,0.00,0.00,0.00,0.00,TRANSFER_TO_WALLET
5,6,CASH Withdrawals,0.00,417050.00,0,32,417050.00,0.00,0.00,0.00,0.00,CASH_WITHDRAWAL
6,7,Transportation,0.00,13330.40,0,21,13330.40,0.00,0.00,0.00,0.00,TRANSPORTATION
7,8,Cash Deposit,46075.00,0.00,1,0,46075.00,185.79,185.79,0.00,0.00,CASH_DEPOSIT
8,9,Transfer out,0.00,619752.10,0,171,619752.10,0.00,0.00,0.00,0.00,TRANSFER_OUT
9,10,Bounce Transaction,3800.00,3800.00,1,1,7600.00,15.83,15.83,42.22,42.22,BOUNCE_TRANSACTION
10,11,Utilities,0.00,48793.84,0,39,48793.84,0.00,0.00,0.00,0.00,UTILITIES
11,12,EMIs,0.00,400858.20,0,31,400858.20,0.00,0.00,0.00,0.00,EMI
12,13,Bank Charges,0.00,867.78,0,8,867.78,0.00,0.00,0.00,0.00,BANK_CHARGE
13,14,Insurance Premium,0.00,7977.07,0,1,7977.07,0.00,0.00,0.00,0.00,INSURANCE_PREMIUM
14,15,Interest Credit,319.20,0.00,2,0,319.20,1.35,1.35,1.99,1.99,INTEREST_CREDIT
15,16,Health Care,0.00,47790.70,0,24,47790.70,0.00,0.00,0.00,0.00,HEALTHCARE
16,17,Cash Back,39.90,0.00,6,0,39.90,0.19,0.19,0.44,0.44,CASH_BACK
17,18,Transfer in,1074982.34,0.00,49,0,1074982.34,4627.28,4627.28,8549.29,8549.29,TRANSFER_IN
18,19,Reversal,8365.70,0.00,3,0,8365.70,36.44,36.44,80.34,80.34,REVERSAL_TXN
19,20,Purchase by Card,902.97,24048.30,2,22,24951.27,3.79,3.79,9.92,9.92,PURCHASE_BY_CARD
20,21,Shopping,0.00,3945.35,0,8,3945.35,0.00,0.00,0.00,0.00,SHOPPING
21,22,Merchant Expenditure,0.00,139345.05,0,98,139345.05,0.00,0.00,0.00,0.00,MERCHANT_EXPENDITURE
22,23,Food,0.00,8350.50,0,11,8350.50,0.00,0.00,0.00,0.00,FOOD

In [22]:
# Category wise summary for last month ONLY

latestMonthCategoryObjects = [] # Latest month category summary

endYear = profileDataDict["dataEndDate"][:4]
endMonth = profileDataDict["dataEndDate"][5:7]

catInd = 0
for catType in bankAnalysisData["completeCategoryWiseAnalysis"]["monthlyCategoryWiseAnalysis"]:
    catInd += 1
    for monthObj in bankAnalysisData["completeCategoryWiseAnalysis"]["monthlyCategoryWiseAnalysis"][catType]:
        if monthObj["year"] == int(endYear) and monthObj["month"] == int(endMonth):
            categoryDict = { "id": catInd, "categoryName": catType}
            categoryDict.update(monthObj)
    
            # Dropping useless keys
            removedKey = categoryDict.pop("minimumCreditAmount", None)
            removedKey = categoryDict.pop("maximumCreditAmount", None)
            removedKey = categoryDict.pop("minimumDebitAmount", None)
            removedKey = categoryDict.pop("maximumDebitAmount", None)

            latestMonthCategoryObjects.append(categoryDict)

latestMonthCategoriesDataDf = pd.DataFrame.from_dict(latestMonthCategoryObjects)
latestMonthCategoriesDataDf

,id,categoryName,year,month,totalCreditAmount,totalDebitAmount,totalCreditTxn,totalDebitTxn,totalCreditDebitAmount,avgCreditAmount,avgDebitAmount,categoryCode
0,1,Credit Card Payment,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,CREDIT_CARD_PAYMENT
1,2,Salary,2022,6,81116.7,0.00,1,0,81116.70,81116.7,0.00,SALARY
2,3,Entertainment,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,ENTERTAINMENT
3,4,Personal Care,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,PERSONAL_CARE
4,5,Transfer to Wallet,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,TRANSFER_TO_WALLET
5,6,CASH Withdrawals,2022,6,0.0,16150.00,0,1,16150.00,0.0,16150.00,CASH_WITHDRAWAL
6,7,Transportation,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,TRANSPORTATION
7,8,Cash Deposit,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,CASH_DEPOSIT
8,9,Transfer out,2022,6,0.0,9989.25,0,15,9989.25,0.0,665.95,TRANSFER_OUT
9,10,Bounce Transaction,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,BOUNCE_TRANSACTION
10,11,Utilities,2022,6,0.0,1120.05,0,2,1120.05,0.0,560.03,UTILITIES
11,12,EMIs,2022,6,0.0,33937.80,0,3,33937.80,0.0,11312.60,EMI
12,13,Bank Charges,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,BANK_CHARGE
13,14,Insurance Premium,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,INSURANCE_PREMIUM
14,15,Interest Credit,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,INTEREST_CREDIT
15,16,Health Care,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,HEALTHCARE
16,17,Cash Back,2022,6,5.7,0.00,1,0,5.70,5.7,0.00,CASH_BACK
17,18,Transfer in,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,TRANSFER_IN
18,19,Reversal,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,REVERSAL_TXN
19,20,Purchase by Card,2022,6,0.0,919.60,0,1,919.60,0.0,919.60,PURCHASE_BY_CARD
20,21,Shopping,2022,6,0.0,342.00,0,1,342.00,0.0,342.00,SHOPPING
21,22,Merchant Expenditure,2022,6,0.0,11592.85,0,7,11592.85,0.0,1656.12,MERCHANT_EXPENDITURE
22,23,Food,2022,6,0.0,0.00,0,0,0.00,0.0,0.00,FOOD

In [23]:
# Analysis of Equities into a table/object using "equitiesData" from equities json
equityDataObject = {}

equityDataObject["investmentValue"] = equitiesData["Account"]["Summary"]["investmentValue"]
equityDataObject["currentValue"] = equitiesData["Account"]["Summary"]["currentValue"]


equityDataObject["holdings"] = []

for holding in equitiesData["Account"]["Summary"]["Investment"][0]["Holdings"]:
    poppedKey = holding["Holding"].pop("isin", None)
    equityDataObject["holdings"].append(holding["Holding"])

equityDataObject

equityHoldingsDf = pd.DataFrame.from_dict(equityDataObject["holdings"])
equityHoldingsDf

,issuerName,units,rate,investmentDateTime,lastTradedPrice,description
0,Reliance Industries Limited,79,2153.15,2004-04-12T13:20:00-05:00,2377.75,
1,HCL Technologies Ltd,34,1021.97,2004-04-12T13:20:00-05:00,923.05,

In [24]:
# Analysis of insurance data from insurance JSON

insuranceSummaryObj = insuranceData["Account"]["Summary"]
insuranceSummaryObj

{'policyName': '',
 'policyNumber': '',
 'eiaNumber': '',
 'sumAssured': '2500000',
 'coverAmount': '2500000',
 'tenureMonths': '240',
 'tenureYears': '20',
 'premiumAmount': '8367.00',
 'policyStartDate': '2015-04-12',
 'policyType': 'TERM',
 'coverType': 'TERM_ROP',
 'premiumFrequency': 'QUARTELY',
 'premiumPaymentYears': '15',
 'premiumPaymentMonths': '180',
 'maturityDate': '2025-04-12',
 'maturityBenefit': '',
 'MoneyBacks': {'MoneyBack': {'date': '2025-04-12',
   'amount': '2500000',
   'description': ''}},
 'ContractClauses': {'ContractClause': {'title': '',
   'subLimit': '',
   'conditions': '',
   'exlcusions': '',
   'amount': '',
   'description': ''}},
 'Covers': {'Cover': {'amount': '', 'description': ''}}}

In [25]:
# Analysis of mutual fund data using Mutual Fund Json
mutualFundsObject = {}

mutualFundsObject["nominee"] = mutualFundData["Account"]["Profile"]["Holders"]["Holder"]["nominee"]
mutualFundsObject["amc"] = mutualFundData["Account"]["Summary"]["Investment"]["Holdings"]["Holding"]["amc"]
mutualFundsObject["dividendType"] = mutualFundData["Account"]["Summary"]["Investment"]["Holdings"]["Holding"]["dividendType"]
mutualFundsObject["units"] = mutualFundData["Account"]["Summary"]["Investment"]["Holdings"]["Holding"]["units"]
mutualFundsObject["rate"] = mutualFundData["Account"]["Summary"]["Investment"]["Holdings"]["Holding"]["rate"]
mutualFundsObject["nav"] = mutualFundData["Account"]["Summary"]["Investment"]["Holdings"]["Holding"]["nav"]
mutualFundsObject["startDate"] = mutualFundData["Account"]["Transactions"]["startDate"]
mutualFundsObject["amount"] = mutualFundData["Account"]["Transactions"]["Transaction"][0]["amount"]

mutualFundsObject

{'nominee': 'NOT-REGISTERED',
 'amc': 'Axis Mutual Fund',
 'dividendType': 'Stock',
 'units': '',
 'rate': '15.83',
 'nav': '16.74',
 'startDate': '2022-09-30',
 'amount': '5000.00'}

In [26]:
##################################################################################################################################
########################### DEFINING LOGIC FOR SEGMENTATION OF USERS BASED ON DIFFERENT ASPECTS ##################################
##################################################################################################################################

In [27]:
# This function is used to identfiy the life stage of person using "age"
def identifyLifeStage(age):
    if age < 20:
        return "Teenager"
    elif age < 22:
        return "Student"
    elif age < 30:
        return "Early employeed"
    elif age < 60:
        return "Mature employeed"
    else: 
        return "Retired"

identifyLifeStage(profileDataDict['age'])

'Early employeed'

In [28]:
# Calculate a person's net income for the year = Salary credited + Investment returns credited - amount invested  
def calcIncome():
    income = 0
    annualSalary= (categoriesDict["Salary"]["totalCreditAmount"]/profileDataDict['monthsOfData']) * 12 # To find aprx annual income
    income += annualSalary + (investmentDataDict["totalCreditAmount"] - investmentDataDict["totalDebitAmount"])
    return income
calcIncome()

874190.725

In [29]:
def findGender(personName):
    nameSplits = personName.split(".")
    
    if nameSplits[0] == 'MR':
        return "Male"
    return "Female"

findGender(profileDataDict["name"])

'Male'

In [30]:
def findCity(address):
    addressSplits = address.split(" ")
    return addressSplits[-1]

findCity(profileDataDict['address'])

'SURAT'

In [31]:
# Creating an object about demographics
demographicsDict = {}

demographicsDict["age"] = profileDataDict["age"]
demographicsDict["lifeStage"] = identifyLifeStage(age)
demographicsDict["gender"] = findGender(profileDataDict["name"])
demographicsDict["city"] = findCity(profileDataDict["address"])
demographicsDict["income"] = calcIncome()

demographicsDict

{'age': 22,
 'lifeStage': 'Early employeed',
 'gender': 'Male',
 'city': 'SURAT',
 'income': 874190.725}

In [32]:
balanceSummaryDf

,monthYear,month,year,eodBalOn5,eodBalOn10,eodBalOn15,eodBalOn20,eodBalOn25,eodBalTotal,eodBalAvg
0,November-2021,11,2021,NaN,NaN,17387.30,30783.42,25093.87,73264.59,24421.53
1,December-2021,12,2021,6423.76,81762.56,26276.86,3769.46,3185.21,121417.85,24283.57
2,January-2022,1,2022,13033.86,62823.36,27550.81,4917.06,2624.71,110949.80,22189.96
3,February-2022,2,2022,7161.91,97209.56,31759.56,2590.76,2780.76,141502.55,28300.51
4,March-2022,3,2022,30388.52,16063.83,69140.33,9151.63,8440.08,133184.39,26636.88
5,April-2022,4,2022,20146.14,110672.21,26001.56,6955.01,10749.92,174524.84,34904.97
6,May-2022,5,2022,7208.63,68591.70,387377.79,37589.92,40244.22,541012.26,108202.45
7,June-2022,6,2022,5026.77,55122.17,NaN,NaN,NaN,60148.94,30074.47

In [33]:
keySummary

{'totalAccounts': 1,
 'creditDebitRatio': 0.97,
 'totalCreditTxn': 71,
 'totalCreditAmount': 1715211.56,
 'totalDebitTxn': 481,
 'totalDebitAmount': 1761167.89,
 'avgMonthlyBalance': 27549.54,
 'last3MonthsAvgMonthlyBalance': 37663.26,
 'last6MonthsAvgMonthlyBalance': 29892.27,
 'last3MonthAvgDebitAmount': 402461.03,
 'last3MonthAvgCreditAmount': 384475.64,
 'volatilityOfBalance': 1.72}

In [34]:
# Budget split of the person

income = demographicsDict["income"]
# Percent wise split of categories  (+5 for upper range)
budgetSplitPercent = {
    'Insurance': 5,
    'Health Care': 5,
    'Food': 10,
    'Transportation': 10,
    'Personal': 5,
    'Recreation': 5,
    'Utilities': 5,
    'EMI/Housing': 25,
    'Savings': 10,
}

lowLimitBudget = {
    'Insurance': 0,
    'Health Care': 0,
    'Food': 0,
    'Transportation': 0,
    'Personal': 0,
    'Recreation': 0,
    'Utilities': 0,
    'EMI/Housing': 0,
    'Savings': 0
} 

upperLimitBudget = {
    'Insurance': 0,
    'Health Care': 0,
    'Food': 0,
    'Transportation': 0,
    'Personal': 0,
    'Recreation': 0,
    'Utilities': 0,
    'EMI/Housing': 0,
    'Savings': 0
} 

for category in budgetSplitPercent:
    lowLimitBudget[category] = budgetSplitPercent[category] * .01 * income
    upperLimitBudget[category] = (budgetSplitPercent[category] + 5) * .01 * income

print("Low:", lowLimitBudget)
print("upper:", upperLimitBudget)

Low: {'Insurance': 43709.536250000005, 'Health Care': 43709.536250000005, 'Food': 87419.07250000001, 'Transportation': 87419.07250000001, 'Personal': 43709.536250000005, 'Recreation': 43709.536250000005, 'Utilities': 43709.536250000005, 'EMI/Housing': 218547.68125, 'Savings': 87419.07250000001}
upper: {'Insurance': 87419.07250000001, 'Health Care': 87419.07250000001, 'Food': 131128.60874999998, 'Transportation': 131128.60874999998, 'Personal': 87419.07250000001, 'Recreation': 87419.07250000001, 'Utilities': 87419.07250000001, 'EMI/Housing': 262257.21749999997, 'Savings': 131128.60874999998}

In [35]:
# Evaluating spends as per budget

categoryToKeyMapper = {
    'Insurance': ['Insurance Premium'],
    'Health Care': ['Health Care'],
    'Food': ['Food'],
    'Transportation': ['Transportation'],
    'Personal': ['Personal Care', 'Shopping', 'Transfer to Wallet', 'Purchase by Card'],
    'Recreation': ['Entertainment'],
    'Utilities': ['Utilities'],
    'EMI/Housing': ['EMIs'],
    'Savings': ['']
}

budgetValues = {
    'Insurance': 0,
    'Health Care': 0,
    'Food': 0,
    'Transportation': 0,
    'Personal': 0,
    'Recreation': 0,
    'Utilities': 0,
    'EMI/Housing': 0,
    'Savings': 0
}

budgetEval = {
    'Insurance': '',
    'Health Care': '',
    'Food': '',
    'Transportation': '',
    'Personal': '',
    'Recreation': '',
    'Utilities': '',
    'EMI/Housing': '',
    'Savings': ''
}

totalAmountExcludingSavings = 0

for category in budgetEval:
    catTotal = 0
    for catKey in categoryToKeyMapper[category]:
        if catKey != '':
            catTotal += categoriesDict[catKey]["totalDebitAmount"] - categoriesDict[catKey]["totalCreditAmount"]
        else: # For savings
            catTotal = demographicsDict["income"] - totalAmountExcludingSavings - categoriesDict["Merchant Expenditure"]["totalDebitAmount"]
    budgetValues[category] = catTotal
    if catTotal < lowLimitBudget[category]:
        budgetEval[category] = 'below'
    elif catTotal >= lowLimitBudget[category] and catTotal <= upperLimitBudget[category]:
        budgetEval[category] = 'on-par'
    else:
        budgetEval[category] = 'above'  
    totalAmountExcludingSavings += catTotal

print(budgetValues)

budgetEval

{'Insurance': 7977.07, 'Health Care': 47790.7, 'Food': 8350.5, 'Transportation': 13330.4, 'Personal': 45958.63, 'Recreation': 405.65, 'Utilities': 48793.84, 'EMI/Housing': 400858.2, 'Savings': 161380.685}

{'Insurance': 'below',
 'Health Care': 'on-par',
 'Food': 'below',
 'Transportation': 'below',
 'Personal': 'on-par',
 'Recreation': 'below',
 'Utilities': 'on-par',
 'EMI/Housing': 'above',
 'Savings': 'above'}

In [36]:
# Different feature flags

featureFlags = {
    'investor': False,
    'mutualFunds': False,
    'FDs': False,
    'insured': False,
    'loans': False,
    'heavyShopper': False,
    'heavyOutsideFood': False,
    'heavyEntertainment': False,
    'heavyUtilities': False,
    'heavyTransportation': False,
    'heavyHealthCare': False,
    "heavyInvestor": False,
    "heavySaver": False,
    "heavyDebit": False,
    "heavyCredit": False,
    "creditCardUser": False,
    'paymentMissedRecently': True,
    'lumpSumReceivedRecently': True
}

def evaluateFlags():
    
    if investmentDataDict["totalDebitAmount"] and investmentDataDict["totalDebitAmount"] > 0:
        featureFlags['investor'] = True
    if mutualFundsObject["amount"] and float(mutualFundsObject["amount"]) > 0:
        featureFlags["mutualFunds"] = True
    if investmentDataDict["subCategoryAnalysis"] and investmentDataDict["subCategoryAnalysis"]["Fixed/Recurring Deposits"]["totalCreditAmount"] > 0:
        featureFlags["FDs"] = True
    if categoriesDict["Insurance Premium"] and categoriesDict["Insurance Premium"]["totalDebitAmount"] > 0:
        featureFlags["insured"] = True
    if categoriesDict["EMIs"] and categoriesDict["EMIs"]["totalDebitAmount"] > 0:
        featureFlags["loans"] = True
    if budgetEval['Personal'] and (budgetEval['Personal'] == 'above' or budgetEval['Personal'] == 'on-par') :
        featureFlags['heavyShopper'] = True
    if budgetEval['Food'] and (budgetEval['Food'] == 'above' or budgetEval['Food'] == 'on-par'):
        featureFlags["heavyOutsideFood"] = True
    if budgetEval["Recreation"] and (budgetEval["Recreation"] == 'above' or budgetEval["Recreation"] == 'on-par'):
        featureFlags["heavyEntertainment"] = True
    if budgetEval["Utilities"] and (budgetEval["Utilities"] == 'above' or budgetEval['Utilities'] == 'on-par'):
        featureFlags["heavyUtilities"] = True
    if budgetEval['Transportation'] and (budgetEval['Transportation'] == 'above' or budgetEval['Transportation'] == 'on-par'):
        featureFlags["heavyTransportation"] = True
    if budgetEval["Health Care"] and (budgetEval["Health Care"] == 'above' or budgetEval['Health Care'] == 'on-par'):
        featureFlags["heavyHealthCare"] = True
    if investmentDataDict["totalDebitAmount"] and investmentDataDict["totalDebitAmount"] > demographicsDict["income"] * 10 * .01:
        featureFlags["heavyInvestor"] = True
    if budgetEval["Savings"] and (budgetEval["Savings"] == 'above'):
        featureFlags["heavySaver"] = True
    if keySummary["creditDebitRatio"] and keySummary["creditDebitRatio"] <= 1:
        featureFlags["heavyDebit"] = True    
    if keySummary["creditDebitRatio"] and keySummary["creditDebitRatio"] > 1:
        featureFlags["heavyCredit"] = True
    if categoriesDict['Credit Card Payment'] and categoriesDict['Credit Card Payment']["totalDebitAmount"] > 0:
        featureFlags["creditCardUser"] = True
    
evaluateFlags()

featureFlags

{'investor': True,
 'mutualFunds': True,
 'FDs': True,
 'insured': True,
 'loans': True,
 'heavyShopper': True,
 'heavyOutsideFood': False,
 'heavyEntertainment': False,
 'heavyUtilities': True,
 'heavyTransportation': False,
 'heavyHealthCare': True,
 'heavyInvestor': False,
 'heavySaver': True,
 'heavyDebit': True,
 'heavyCredit': False,
 'creditCardUser': True,
 'paymentMissedRecently': True,
 'lumpSumReceivedRecently': True}

In [37]:
categoriesDict

{'Credit Card Payment': {'id': 1,
  'categoryName': 'Credit Card Payment',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 5985.0,
  'totalCreditTxn': 0,
  'totalDebitTxn': 1,
  'totalCreditDebitAmount': 5985.0,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'CREDIT_CARD_PAYMENT'},
 'Salary': {'id': 2,
  'categoryName': 'Salary',
  'totalCreditAmount': 580726.45,
  'totalDebitAmount': 0.0,
  'totalCreditTxn': 7,
  'totalDebitTxn': 0,
  'totalCreditDebitAmount': 580726.45,
  'avgMonthlyCredit': 2791.45,
  'avgMonthlyDebit': 2791.45,
  'last3MonthAvgCreditAmount': 3708.08,
  'last3MonthAvgDebitAmount': 3708.08,
  'categoryCode': 'SALARY'},
 'Entertainment': {'id': 3,
  'categoryName': 'Entertainment',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 405.65,
  'totalCreditTxn': 0,
  'totalDebitTxn': 1,
  'totalCreditDebitAmount': 405.65,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'ENTERTAINMENT'},
 'Personal Care': {'id': 4,
  'categoryName': 'Personal Care',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 5727.55,
  'totalCreditTxn': 0,
  'totalDebitTxn': 1,
  'totalCreditDebitAmount': 5727.55,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'PERSONAL_CARE'},
 'Transfer to Wallet': {'id': 5,
  'categoryName': 'Transfer to Wallet',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 13140.4,
  'totalCreditTxn': 0,
  'totalDebitTxn': 11,
  'totalCreditDebitAmount': 13140.4,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'TRANSFER_TO_WALLET'},
 'CASH Withdrawals': {'id': 6,
  'categoryName': 'CASH Withdrawals',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 417050.0,
  'totalCreditTxn': 0,
  'totalDebitTxn': 32,
  'totalCreditDebitAmount': 417050.0,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'CASH_WITHDRAWAL'},
 'Transportation': {'id': 7,
  'categoryName': 'Transportation',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 13330.4,
  'totalCreditTxn': 0,
  'totalDebitTxn': 21,
  'totalCreditDebitAmount': 13330.4,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'TRANSPORTATION'},
 'Cash Deposit': {'id': 8,
  'categoryName': 'Cash Deposit',
  'totalCreditAmount': 46075.0,
  'totalDebitAmount': 0.0,
  'totalCreditTxn': 1,
  'totalDebitTxn': 0,
  'totalCreditDebitAmount': 46075.0,
  'avgMonthlyCredit': 185.79,
  'avgMonthlyDebit': 185.79,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'CASH_DEPOSIT'},
 'Transfer out': {'id': 9,
  'categoryName': 'Transfer out',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 619752.1,
  'totalCreditTxn': 0,
  'totalDebitTxn': 171,
  'totalCreditDebitAmount': 619752.1,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'TRANSFER_OUT'},
 'Bounce Transaction': {'id': 10,
  'categoryName': 'Bounce Transaction',
  'totalCreditAmount': 3800.0,
  'totalDebitAmount': 3800.0,
  'totalCreditTxn': 1,
  'totalDebitTxn': 1,
  'totalCreditDebitAmount': 7600.0,
  'avgMonthlyCredit': 15.83,
  'avgMonthlyDebit': 15.83,
  'last3MonthAvgCreditAmount': 42.22,
  'last3MonthAvgDebitAmount': 42.22,
  'categoryCode': 'BOUNCE_TRANSACTION'},
 'Utilities': {'id': 11,
  'categoryName': 'Utilities',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 48793.84,
  'totalCreditTxn': 0,
  'totalDebitTxn': 39,
  'totalCreditDebitAmount': 48793.84,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'UTILITIES'},
 'EMIs': {'id': 12,
  'categoryName': 'EMIs',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 400858.2,
  'totalCreditTxn': 0,
  'totalDebitTxn': 31,
  'totalCreditDebitAmount': 400858.2,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'EMI'},
 'Bank Charges': {'id': 13,
  'categoryName': 'Bank Charges',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 867.78,
  'totalCreditTxn': 0,
  'totalDebitTxn': 8,
  'totalCreditDebitAmount': 867.78,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'BANK_CHARGE'},
 'Insurance Premium': {'id': 14,
  'categoryName': 'Insurance Premium',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 7977.07,
  'totalCreditTxn': 0,
  'totalDebitTxn': 1,
  'totalCreditDebitAmount': 7977.07,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'INSURANCE_PREMIUM'},
 'Interest Credit': {'id': 15,
  'categoryName': 'Interest Credit',
  'totalCreditAmount': 319.2,
  'totalDebitAmount': 0.0,
  'totalCreditTxn': 2,
  'totalDebitTxn': 0,
  'totalCreditDebitAmount': 319.2,
  'avgMonthlyCredit': 1.35,
  'avgMonthlyDebit': 1.35,
  'last3MonthAvgCreditAmount': 1.99,
  'last3MonthAvgDebitAmount': 1.99,
  'categoryCode': 'INTEREST_CREDIT'},
 'Health Care': {'id': 16,
  'categoryName': 'Health Care',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 47790.7,
  'totalCreditTxn': 0,
  'totalDebitTxn': 24,
  'totalCreditDebitAmount': 47790.7,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'HEALTHCARE'},
 'Cash Back': {'id': 17,
  'categoryName': 'Cash Back',
  'totalCreditAmount': 39.9,
  'totalDebitAmount': 0.0,
  'totalCreditTxn': 6,
  'totalDebitTxn': 0,
  'totalCreditDebitAmount': 39.9,
  'avgMonthlyCredit': 0.19,
  'avgMonthlyDebit': 0.19,
  'last3MonthAvgCreditAmount': 0.44,
  'last3MonthAvgDebitAmount': 0.44,
  'categoryCode': 'CASH_BACK'},
 'Transfer in': {'id': 18,
  'categoryName': 'Transfer in',
  'totalCreditAmount': 1074982.34,
  'totalDebitAmount': 0.0,
  'totalCreditTxn': 49,
  'totalDebitTxn': 0,
  'totalCreditDebitAmount': 1074982.34,
  'avgMonthlyCredit': 4627.28,
  'avgMonthlyDebit': 4627.28,
  'last3MonthAvgCreditAmount': 8549.29,
  'last3MonthAvgDebitAmount': 8549.29,
  'categoryCode': 'TRANSFER_IN'},
 'Reversal': {'id': 19,
  'categoryName': 'Reversal',
  'totalCreditAmount': 8365.7,
  'totalDebitAmount': 0.0,
  'totalCreditTxn': 3,
  'totalDebitTxn': 0,
  'totalCreditDebitAmount': 8365.7,
  'avgMonthlyCredit': 36.44,
  'avgMonthlyDebit': 36.44,
  'last3MonthAvgCreditAmount': 80.34,
  'last3MonthAvgDebitAmount': 80.34,
  'categoryCode': 'REVERSAL_TXN'},
 'Purchase by Card': {'id': 20,
  'categoryName': 'Purchase by Card',
  'totalCreditAmount': 902.97,
  'totalDebitAmount': 24048.3,
  'totalCreditTxn': 2,
  'totalDebitTxn': 22,
  'totalCreditDebitAmount': 24951.27,
  'avgMonthlyCredit': 3.79,
  'avgMonthlyDebit': 3.79,
  'last3MonthAvgCreditAmount': 9.92,
  'last3MonthAvgDebitAmount': 9.92,
  'categoryCode': 'PURCHASE_BY_CARD'},
 'Shopping': {'id': 21,
  'categoryName': 'Shopping',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 3945.35,
  'totalCreditTxn': 0,
  'totalDebitTxn': 8,
  'totalCreditDebitAmount': 3945.35,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'SHOPPING'},
 'Merchant Expenditure': {'id': 22,
  'categoryName': 'Merchant Expenditure',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 139345.05,
  'totalCreditTxn': 0,
  'totalDebitTxn': 98,
  'totalCreditDebitAmount': 139345.05,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'MERCHANT_EXPENDITURE'},
 'Food': {'id': 23,
  'categoryName': 'Food',
  'totalCreditAmount': 0.0,
  'totalDebitAmount': 8350.5,
  'totalCreditTxn': 0,
  'totalDebitTxn': 11,
  'totalCreditDebitAmount': 8350.5,
  'avgMonthlyCredit': 0.0,
  'avgMonthlyDebit': 0.0,
  'last3MonthAvgCreditAmount': 0.0,
  'last3MonthAvgDebitAmount': 0.0,
  'categoryCode': 'FOOD'}}

In [38]:
# Dividing each individual into different finance personality types-> One can fit into multiple as well

financePersonalityTypes = ["investors", "savers", "big spenders", "debtors", "shoppers"]

# Atleast 2/3rd of the features should be satisfied for each personality type
personalityFeatures = {
    "investors": ["heavyInvestor"],
    "savers": ["heavySaver"],
    "big spenders": ["heavyCredit", "heavyShopper", "heavyEntertainment", "heavyOutsideFood", "heavyTransportation"],
    "debtors": ["heavyDebit"],
    "shoppers": ["heavyShopper"]    
}


personalityIdentifier = {
    "investors": False,
    "savers": False,
    "big spenders": False,
    "debtors": False,
    "shoppers": False    
}


for personalityType in personalityFeatures:
    
    totalFeatures = len(personalityFeatures[personalityType])
    if totalFeatures == 1:
        requiredNoOfFeaturesToSatisfy = 1
    else:    
        requiredNoOfFeaturesToSatisfy = int(2 * totalFeatures/3)
    trueCount = 0

    for feature in personalityFeatures[personalityType]:
        if featureFlags[feature]: 
            trueCount += 1
    if trueCount >= requiredNoOfFeaturesToSatisfy:
        personalityIdentifier[personalityType] = True

personalityIdentifier

{'investors': False,
 'savers': True,
 'big spenders': False,
 'debtors': True,
 'shoppers': True}

In [39]:
# Putting the user into miscellaneous segments

miscTypes = {
    "paymentForgetful": False,
    "lumpSumReceiver": False,
    "underCoveredInsurance": False, # Cover should be atleast 10x the annual income
    "studentLoanRequired": False, # Based on life stage
    "foodie": False, # Based on heavyOutsideFood,
    "shopper": False, #  "   "  heavyShopping
    "entertainMax": False, # "  " heavyEntertainment
    "creditCardUser": False, # creditCardUser feature flag
    "nomineeMF": False, # Based on mutualFundsObject 'nominee'
}

annualIncome = (categoriesDict["Salary"]["totalCreditAmount"]/profileDataDict['monthsOfData']) * 12 # To find aprx annual income
# print(annualIncome, float(insuranceSummaryObj['sumAssured']))

def evaluateMiscTypes():
    if featureFlags['paymentMissedRecently']:
        miscTypes["paymentForgetful"] = True
    if featureFlags['lumpSumReceivedRecently']:
        miscTypes['lumpSumReceiver'] = True
    if float(insuranceSummaryObj['sumAssured']) < annualIncome * 10:
        miscTypes['underCoveredInsurance'] = True
    if demographicsDict['lifeStage'] == 'Student':
        miscTypes["studentLoanRequired"] = True
    if featureFlags['heavyOutsideFood']:
        miscTypes["foodie"] = True
    if featureFlags['heavyShopper']:
        miscTypes["shopper"] = True
    if featureFlags["heavyEntertainment"]:
        miscTypes["entertainMax"] = True
    if featureFlags["creditCardUser"]:
        miscTypes["creditCardUser"] = True
    if mutualFundsObject["nominee"] == 'REGISTERED':
        miscTypes['nomineeMF'] = True

evaluateMiscTypes()
miscTypes

{'paymentForgetful': True,
 'lumpSumReceiver': True,
 'underCoveredInsurance': True,
 'studentLoanRequired': False,
 'foodie': False,
 'shopper': True,
 'entertainMax': False,
 'creditCardUser': True,
 'nomineeMF': False}

In [41]:
# Loading all nudges data

with open('../data/nudgesContent.json') as json_file:
        segmentNudgesObject = json.load(json_file)

segmentNudgesObject

{'investors': {'mainText': 'Do you want to diverify your investments? Check this out!',
  'smallText': 'Diversification reduces the impact of market volatility'},
 'savers': {'mainText': 'You have been saving up a lot in your bank accounts, why not put it in a lock-in free Fixed Deposit for better returns?',
  'smallText': 'One can earn upto 7% interest on FDs'},
 'big spenders': {'mainText': 'We notice you are a big spender, get this credit card for a higher credit limit!',
  'smallText': 'More than 50% of our users with similar spends use this card!'},
 'debtors': {'mainText': 'Start investing today to save and get returns at the same time! Checkout our Mutual Funds...',
  'smallText': 'Investing into stable instruments can help save and even grow your money gradually'},
 'shoppers': {'mainText': 'Shopping is the best medicine, we have a credit card just for you!',
  'smallText': 'Get higher credit limits and many offers for the shopper in you!'},
 'paymentForgetful': {'mainText': 'Reminder: Your wifi bill will be due in 3 days, pay early!',
  'smallText': 'You missed 2 bill payments in the last 3 months. Pay early and avoid the late fees.'},
 'lumpSumReceiver': {'mainText': 'You have received lump sum amount in your bank account this week, would you like to invest in Mutual Funds?',
  'smallText': 'Mutual Funds can give more than 10% average annualized return subject to market risk'},
 'underCoveredInsurance': {'mainText': 'On the basis of your demographic and income, you are under insured. Would you like to opt for a better life insurance?',
  'smallText': '80% customers of your age opt for a 1Cr+ life cover!'},
 'studentLoanRequired': {'mainText': 'You are going to graduate soon. Any plans for higher education? Check out pre-approved student loans just for you!',
  'smallText': 'Student loans cover entire cost associated with the degree and the interest rates are lower'},
 'foodie': {'mainText': 'People who love to eat are always the best people! Why not go for the best card with offers on leading food ordering platforms',
  'smallText': 'Our cards provide extra discounts on Zomato, Swiggy and many more.....'},
 'shopper': {'mainText': 'Shopping is the best medicine, we have a credit card just for you!',
  'smallText': 'Get higher credit limits and many offers for the shopper in you!'},
 'entertainMax': {'mainText': 'Checkout this card for various offers accross book my show and OTT platforms',
  'smallText': 'Users of this card save upto 30% on entertainment platforms'},
 'creditCardUser': {'mainText': 'Want to increase your credit score? Have a look!',
  'smallText': 'People with higher credit scores get potentially lower interest rates'},
 'nomineeMF': {'mainText': "We notice you haven't registered your Nominee for the mutual funds you have invested in. Want to add it today?",
  'smallText': 'Having a nominee saves the trouble to your loved ones'}}

In [42]:
# Identifying nudges for the user based on his personality and misc segments

possibleNudgesForUser = []

# Based on financePersonality
for type in personalityIdentifier:
    if personalityIdentifier[type]:
        possibleNudgesForUser.append(segmentNudgesObject[type])

# Based on miscType
for type in miscTypes:
    if miscTypes[type]:
        possibleNudgesForUser.append(segmentNudgesObject[type])

possibleNudgesForUser

[{'mainText': 'You have been saving up a lot in your bank accounts, why not put it in a lock-in free Fixed Deposit for better returns?',
  'smallText': 'One can earn upto 7% interest on FDs'},
 {'mainText': 'Start investing today to save and get returns at the same time! Checkout our Mutual Funds...',
  'smallText': 'Investing into stable instruments can help save and even grow your money gradually'},
 {'mainText': 'Shopping is the best medicine, we have a credit card just for you!',
  'smallText': 'Get higher credit limits and many offers for the shopper in you!'},
 {'mainText': 'Reminder: Your wifi bill will be due in 3 days, pay early!',
  'smallText': 'You missed 2 bill payments in the last 3 months. Pay early and avoid the late fees.'},
 {'mainText': 'You have received lump sum amount in your bank account this week, would you like to invest in Mutual Funds?',
  'smallText': 'Mutual Funds can give more than 10% average annualized return subject to market risk'},
 {'mainText': 'On the basis of your demographic and income, you are under insured. Would you like to opt for a better life insurance?',
  'smallText': '80% customers of your age opt for a 1Cr+ life cover!'},
 {'mainText': 'Shopping is the best medicine, we have a credit card just for you!',
  'smallText': 'Get higher credit limits and many offers for the shopper in you!'},
 {'mainText': 'Want to increase your credit score? Have a look!',
  'smallText': 'People with higher credit scores get potentially lower interest rates'}]

In [44]:
# Dumping possibleNudges into json file

nudgesData = {"nudges": possibleNudgesForUser} 
nudgesDataJsonPath = '../output-data/nudgesData-' + mobileNumber + '.json'

with open(nudgesDataJsonPath, 'w') as fp:
    json.dump(nudgesData, fp)

In [45]:
# Dynamic widgets

# Loading all widgets content
with open('../data/widgetsContent.json') as json_file:
        widgetsObject = json.load(json_file)

widgetsObject

{'Accounts': 'Manage all your accounts in one place',
 'Loans': 'Explore all kinds of different loans as per your needs',
 'Deposits': 'Save and grow your money in fixed and recurring deposits',
 'Cards': 'Manage your existing cards or choose from a wide range of cards to enjoy special privileges, offers and cashback points!',
 'Investments': 'Invest in different instruments for better returns on your money',
 'Insurance': 'Get Medical and Life insured with our customer friendly plans',
 'Payments': 'Make all kinds of bill payments and earn cashback'}

In [49]:
# Evaluating personalized widgets suitable for the the user

priorityWidgetsOrder = [] # Order in which widgets are important to the customer

priorityWidgetsOrder = [
    {'Investments': 'Invest in different instruments for better returns on your money'}, 
    {'Deposits': 'Save and grow your money in fixed and recurring deposits'}, 
    {'Payments': 'Make all kinds of bill payments and earn cashback'}, 
    {'Insurance': 'Get Medical and Life insured with our customer friendly plans'}, 
    {'Cards': 'Manage your existing cards or choose from a wide range of cards to enjoy special privileges, offers and cashback points!'}, 
    {'Accounts': 'Manage all your accounts in one place'},
    {'Loans': 'Explore all kinds of different loans as per your needs'}
    ]


priorityWidgetsOrder

[{'Investments': 'Invest in different instruments for better returns on your money'},
 {'Deposits': 'Save and grow your money in fixed and recurring deposits'},
 {'Payments': 'Make all kinds of bill payments and earn cashback'},
 {'Insurance': 'Get Medical and Life insured with our customer friendly plans'},
 {'Cards': 'Manage your existing cards or choose from a wide range of cards to enjoy special privileges, offers and cashback points!'},
 {'Accounts': 'Manage all your accounts in one place'},
 {'Loans': 'Explore all kinds of different loans as per your needs'}]

In [51]:
# Dumping possible widgets into json

widgetsData = {"widgetsOrder": priorityWidgetsOrder}  
widgetsDataJsonPath = '../output-data/widgetsData-' + mobileNumber + '.json'
with open(widgetsDataJsonPath, 'w') as fp:
    json.dump(widgetsData, fp)

In [152]:
##############################################User 2 data#############################################

In [153]:
# Nudges sample for 2nd person - 9987600001 , 3742421256

segPersonalityTypes = ["studentLoanRequired", "foodie", "big spenders", "savers"]
possibleNudgesForUser2 = []

for type in segPersonalityTypes:
    possibleNudgesForUser2.append(segmentNudgesObject[type])

possibleNudgesForUser2

[{'mainText': 'You are going to graduate soon. Any plans for higher education? Check out pre-approved student loans just for you!',
  'smallText': 'Student loans cover entire cost associated with the degree and the interest rates are lower'},
 {'mainText': 'People who love to eat are always the best people! Why not go for the best card with offers on leading food ordering platforms',
  'smallText': 'Our cards provide extra discounts on Zomato, Swiggy and many more.....'},
 {'mainText': 'We notice you are a big spender, get this credit card for a higher credit limit!',
  'smallText': 'More than 50% of our users with similar spends use this card!'},
 {'mainText': 'You have been saving up a lot in your bank accounts, why not put it in a lock-in free Fixed Deposit for better returns?',
  'smallText': 'One can earn upto 7% interest on FDs'}]

In [154]:
# Dumping possibleNudges for user2 into json file

nudgesDataUser2 = {"nudges": possibleNudgesForUser2}   
with open('../output-data/nudgesDataUser2.json', 'w') as fp:
    json.dump(nudgesDataUser2, fp)

In [155]:
# Evaluating personalized widgets suitable for the the user 2 9987600001 , 3742421256


priorityWidgetsOrder['9987600001'] = [
    {'Cards': 'Manage your existing cards or choose from a wide range of cards to enjoy special privileges, offers and cashback points!'}, 
    {'Loans': 'Explore all kinds of different loans as per your needs'},
    {'Accounts': 'Manage all your accounts in one place'},
    {'Payments': 'Make all kinds of bill payments and earn cashback'},
    {'Investments': 'Invest in different instruments for better returns on your money'}, 
    {'Deposits': 'Save and grow your money in fixed and recurring deposits'},
    {'Insurance': 'Get Medical and Life insured with our customer friendly plans'}
    ]


priorityWidgetsOrder

{'8037988169': [{'Investments': 'Invest in different instruments for better returns on your money'},
  {'Deposits': 'Save and grow your money in fixed and recurring deposits'},
  {'Payments': 'Make all kinds of bill payments and earn cashback'},
  {'Insurance': 'Get Medical and Life insured with our customer friendly plans'},
  {'Cards': 'Manage your existing cards or choose from a wide range of cards to enjoy special privileges, offers and cashback points!'},
  {'Accounts': 'Manage all your accounts in one place'},
  {'Loans': 'Explore all kinds of different loans as per your needs'}],
 '9987600001': [{'Cards': 'Manage your existing cards or choose from a wide range of cards to enjoy special privileges, offers and cashback points!'},
  {'Loans': 'Explore all kinds of different loans as per your needs'},
  {'Accounts': 'Manage all your accounts in one place'},
  {'Payments': 'Make all kinds of bill payments and earn cashback'},
  {'Investments': 'Invest in different instruments for better returns on your money'},
  {'Deposits': 'Save and grow your money in fixed and recurring deposits'},
  {'Insurance': 'Get Medical and Life insured with our customer friendly plans'}]}

In [52]:
# Getting personalized insurance recommendation

coverAmountRecom = 10*demographicsDict["income"]
if coverAmountRecom > 5000000:
    roundOffCover = str(math.ceil(coverAmountRecom/(10**7))) + 'Crore' # To next crore
else:
    roundOffCover = '50Lakhs'
ageRecom = 60

insuranceRecomObj = {
    "lifeCoverAmount": roundOffCover,
    "coverTillAge": ageRecom,
    "annualPremium": '₹7063',
    "insuranceName": "IndiaFirst Life Insurance promoted by Bank of Baroda"
}

insuranceRecomJsonPath = '../output-data/insuranceRecommendationData-' + mobileNumber + '.json'

with open(insuranceRecomJsonPath, 'w') as fp:
    json.dump(insuranceRecomObj, fp)